name: golangci-lint
on:
  push:
    paths:
      - 'relay/**'
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          working-directory: relay
          args: --timeout=30m --issues-exit-code=0
          skip-cache: true
          install-mode: "binary"

# To run locally:
#     go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.3
